### ISSUE TITLE
预测报错

### ISSUE THREAD

**Issue by 18810031387** [KyanChen/TTP#3]
(pytorch) C:\00zml\00xiangmu\2023\变化监测\TTP-release>python image_demo_with_cdinferencer.py ${C:\00zml\00xiangmu\2023\变化监测\BIT_CD-master\data\lw_building_en_cb_fu\
train\A\211.png} ${C:\00zml\00xiangmu\2023\变化监测\BIT_CD-master\data\lw_building_en_cb_fu\train\B\211.png} configs/TTP/ttp_sam_large_levircd_infer.py --checkpoint ${C:
\00zml\00xiangmu\2023\变化监测\TTP-release\lw\pretrain\epoch_270.pth} --out-dir ${C:\00zml\00xiangmu\2023\变化监测\BIT_CD-master\data\lw_building_en_cb_fu\train}       

 
Traceback (most recent call last):
  File "image_demo_with_cdinferencer.py", line 58, in <module>
    main()
  File "image_demo_with_cdinferencer.py", line 37, in main
    mmseg_inferencer = OpenCDInferencer(
TypeError: __init__() got multiple values for argument 'classes'

**Comment by KyanChen** [comment]
没有使用过image_demo_with_cdinferencer.py，可能存在bug
