### ISSUE TITLE
模型导出问题

### ISSUE THREAD

**Issue by nzbanana** [KyanChen/TTP#7]
当我使用”TTP/tools/deployment/pytorch2torchscript.py“尝试将模型导出时出现问题。
(nz) [root@localhost nz]# /home/miniconda3/envs/nz/bin/python /home/data/nz/TTP/pytorch2torchscript.py
/home/data/nz/TTP/mmseg/models/builder.py:44: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  warnings.warn(
Traceback (most recent call last):
  File "/home/data/nz/TTP/pytorch2torchscript.py", line 178, in <module>
    segmentor = build_segmentor(
  File "/home/data/nz/TTP/mmseg/models/builder.py", line 49, in build_segmentor
    assert cfg.get('test_cfg') is None or test_cfg is None, \
AssertionError: test_cfg specified in both outer field and model field 

这里将test_cfg替换成train的config/TPP/ttp_sam_large_levircd_infer.py会产生新的问题
(nz) [root@localhost nz]# /home/miniconda3/envs/nz/bin/python /home/data/nz/TTP/pytorch2torchscript.py
Traceback (most recent call last):
  File "/home/data/nz/TTP/pytorch2torchscript.py", line 178, in <module>
    segmentor = build_segmentor(
  File "/home/data/nz/TTP/mmseg/models/builder.py", line 51, in build_segmentor
    return SEGMENTORS.build(
  File "/home/miniconda3/envs/nz/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/miniconda3/envs/nz/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/miniconda3/envs/nz/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'SiamEncoderDecoder is not in the mmseg::model registry. Please check whether the value of `SiamEncoderDecoder` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

请问正确的test_cfg应该如何设置，或者是否是我的其他操作造成了这些错误，期待您的解答

**Comment by KyanChen** [comment]
没有尝试过模型转换，建议自己写torchscript的转换代码
